{
 "title": "Logging Dashboard via Loki",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kubernetes_namespace_name",
    "label": "Service",
    "query": "label_values({kubernetes_namespace_name=~\".+\"}, kubernetes_namespace_name)"
   },
   {
    "name": "kubernetes_container_name",
    "label": "Service",
    "query": "label_values({kubernetes_container_name=~\".+\"}, kubernetes_container_name)"
   },
   {
    "name": "kubernetes_pod_name",
    "label": "Pod",
    "query": "label_values({kubernetes_container_name=\"$kubernetes_container_name\"}, kubernetes_pod_name)"
   },
   {
    "name": "stream",
    "label": "Stream",
    "query": "label_values({kubernetes_container_name=\"$kubernetes_container_name\"}, stream)"
   },
   { "name": "searchable_pattern", "label": "Search (case insensitive)" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "singlestat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({kubernetes_container_name=\"$kubernetes_container_name\", stream=~\"$stream\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "singlestat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({kubernetes_container_name=\"$kubernetes_container_name\", stream=~\"$stream\", kubernetes_pod_name=~\"$kubernetes_pod_name\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{kubernetes_container_name=\"$kubernetes_container_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", stream=~\"$stream\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  }
 ]
}